# Generated by Django 6.1 on 2026-09-02 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('USER', '普通用户'), ('ADMIN', '管理员')], default='USER', max_length=20),
        ),
    ]
