# Generated by Django 6.1 on 2026-09-02 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userprofile_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='is_approved',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='status',
            field=models.CharField(choices=[('PENDING', '等待审核'), ('APPROVED', '已通过'), ('REJECTED', '已拒绝')], default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('ADMIN', '管理员'), ('USER', '普通用户')], default='USER', max_length=20),
        ),
    ]
