# Generated by Django 6.1 on 2026-09-04 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_userprofile_is_approved_userprofile_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='approved_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='status',
            field=models.CharField(choices=[('PENDING', '等待审核'), ('APPROVED', '已通过'), ('REJECTED', '已拒绝'), ('DISABLED', '已禁用')], default='PENDING', max_length=20),
        ),
    ]
