# Generated by Django 6.1 on 2026-09-02 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockrecord',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='stock_records/'),
        ),
        migrations.AlterField(
            model_name='item',
            name='status',
            field=models.CharField(choices=[('正常', '正常'), ('停用', '停用')], default='正常', max_length=20),
        ),
        migrations.AlterField(
            model_name='stockrecord',
            name='type',
            field=models.CharField(choices=[('IN', '入库'), ('OUT', '借出'), ('RETURN', '归还')], max_length=20),
        ),
    ]
