# Generated by Django 6.1 on 2026-09-02 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_stockrecord_image_alter_item_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stockrecord',
            name='image',
        ),
        migrations.AddField(
            model_name='stockrecord',
            name='location_image',
            field=models.ImageField(blank=True, null=True, upload_to='location_records/'),
        ),
    ]
