# Generated by Django 6.1 on 2026-09-05 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_remove_stockrecord_image_stockrecord_location_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Attribute',
            new_name='ItemAttribute',
        ),
        migrations.AddField(
            model_name='item',
            name='category',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='item',
            name='location',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='stockrecord',
            name='remark',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
