# Generated by Django 6.1 on 2026-09-05 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_rename_attribute_itemattribute_item_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockrecord',
            name='reason',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
